import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/navigation";
import Header from "../components/Header";
const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "../components/costum/theme-provider";
export const metadata: Metadata = {
  title: "Todolist App",
  description: "Generated by create Todolist App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <section className="flex w-full">
            <Navbar />
            <section className="w-full">
              <Header />
              <main className="px-6 py-4">{children}</main>
            </section>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
